#!/bin/bash
#
# env vars passed from CloudCenter
# $SALTMASTER = IP or DNS name of the Salt Master node
# 

exec > >(tee -a /usr/local/osmosix/logs/service.log) 2>&1

OSSVC_HOME=/usr/local/osmosix/service
. /usr/local/osmosix/etc/.osmosix.sh
. /usr/local/osmosix/etc/userenv
. $OSSVC_HOME/utils/cfgutil.sh
. $OSSVC_HOME/utils/install_util.sh
. $OSSVC_HOME/utils/os_info_util.sh

cmd=$1
SVCNAME="saltstack-minion"
SVCHOME="$OSSVC_HOME/$SVCNAME"
USER_ENV="/usr/local/osmosix/etc/userenv"


case $cmd in
	install)
		log "[INSTALL] Installing $SVCNAME bootstrap scripts"
		agentSendLogMessage "Installing SaltStack Minion Scripts" 
		sudo yum install wget -y
		wget -O bootstrap-salt.sh https://bootstrap.saltstack.com/
		;;
	deploy)
		log "[DEPLOY] Deploying $SVCNAME packages using salt bootstrap"
		agentSendLogMessage "Deploying SaltStack BootStrap service"
		sudo sh bootstrap-salt.sh -A 35.197.38.177
		;;
	configure)
		log "[CONFIGURE] Configuring $SVCNAME"
		;;
	start)
		log "[START] Starting $SVCNAME Service"
		agentSendLogMessage "Starting SaltStack Minion Daemon" 
		sudo salt-minion -d
		log "[START] $SVCNAME successfully started."
		;;
	stop)
		log "[STOP] Invoking pre-stop user script"
		log "[STOP] Stopping $SVCNAME"
		sudo service salt-minion stop
		log "[STOP] $SVCNAME successfully stopped."
		;;
	restart)
		log "[RESTART] Invoking pre-restart user script"
		log "[RESTART] Restarting $SVCNAME"
                sudo service salt-minion stop
                sudo salt-minion -d
		log "[RESTART] Invoking post-restart user script"
		;;
	reload)
		log "[RELOAD] Invoking pre-reload user script"
		if [ ! -z $cliqrUserScript -a -f $cliqrUserScript ]; then
			$cliqrUserScript 7 $cliqrUserScriptParams
		fi

		log "[RELOAD] Reloding $SVCNAME settings"

		log "[RELOAD] Invoking post-reload user script"
		if [ ! -z $cliqrUserScript -a -f $cliqrUserScript ]; then
			$cliqrUserScript 8 $cliqrUserScriptParams
		fi
		log "[RELOAD] $SVCNAME successfully reloaded."
		;;
	cleanup)

		;;
	upgrade)
		log "[UPGRADE] Upgrading."
		;;
	*)
		log "[ERROR] unknown command"
		exit 127
		;;
esac
